# Program Filename: makefile
# Author: Vijay Kumar
# Date: 1/22/16
# Description: Assignment 2 - Grocery List

default: main.cpp Item.cpp List.cpp
	g++ -std=c++0x main.cpp Item.cpp List.cpp  -o gro
clean:
	$(RM) gro
 		
