# Program Filename: makefile
# Author: Vijay Kumar
# Date: 1/13/16
# Description: Conway's Game of Life

default: main.cpp startingPoint1.cpp print.cpp deadAlive.cpp
	g++ -std=c++0x main.cpp startingPoint1.cpp print.cpp deadAlive.cpp  -o life
clean:
	$(RM) life
