# name: makefile
# Author: Vijay Kumar
# Date: 3/11/16
# Description: Final

default: Game.cpp main1.cpp Airport.cpp Bar.cpp Diner.cpp Door1.cpp Door2.cpp Door3.cpp Hero.cpp Library.cpp MainFrame.cpp MonarchTowers.cpp Space.cpp Street.cpp Winner.cpp
	g++ -std=c++0x Game.cpp main1.cpp Airport.cpp Bar.cpp Diner.cpp Door1.cpp Door2.cpp Door3.cpp Hero.cpp Library.cpp MainFrame.cpp MonarchTowers.cpp Space.cpp Street.cpp Winner.cpp  -o 100

clean:
	$(RM) 100
 			 		

